name: Build Projects

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  # Récupérer également les sous-modules imbriqués

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Build projects
      run: |
        chmod +x build.sh
        ./build.sh

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive  # Récupérer également les sous-modules imbriqués

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Update PATH
        run: |
          echo "C:\hostedtoolcache\windows\Python\3.11.x\x64\Scripts;C:\hostedtoolcache\windows\Python\3.11.x\x64" >> $env:GITHUB_PATH

      - name: Install CMake
        run: choco install cmake -y

      - name: Install Visual Studio Build Tools
        run: choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd fpdb-3
          python.exe -m pip install -r requirements.txt

      - name: Build projects
        run: |
          ./build.sh

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Build projects
      run: |
        chmod +x build.sh
        ./build.sh
