name: Build pypoker-eval and fpdb-3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements.txt
    - name: Build pypoker-eval
      run: |
        cd fpdb-3/pypoker-eval
        .\build.sh
    - name: Build fpdb-3
      run: |
        .\build_fpdb.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-windows
        path: fpdb-3/dist/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb1 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xinerama0 libxkbcommon-x11-0 libxcb-xfixes0 fuse libfuse2
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements-linux.txt
    - name: Build pypoker-eval
      run: |
        cd fpdb-3/pypoker-eval
        ./build.sh
    - name: Build fpdb-3
      run: |
        ./build_fpdb-linux.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-linux
        path: fpdb-3/*

  build-macos-intel:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements_macos.txt
        brew install pyqt@5
    - name: Build pypoker-eval
      run: |
        cd fpdb-3/pypoker-eval
        ./build.sh
    - name: Build fpdb-3
      run: |
        ./build_fpdb-osx.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-macos-intel
        path: fpdb-3/dist/*

  build-macos-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements_macos.txt
        brew install pyqt@5
    - name: Build pypoker-eval
      run: |
        cd fpdb-3/pypoker-eval
        ./build.sh
    - name: Build fpdb-3
      run: |
        ./build_fpdb-osx.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-macos-arm
        path: fpdb-3/dist/*