name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cmake
        pip install -r requirements.txt

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build

    - name: Copy pypokereval.pyd
      run: |
        Copy-Item ".\build\Release\pypokereval.pyd" ".\_pokereval_3_11.pyd"
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build fpdb-3
      run: |
        chmaod +x build_fpdb.sh
        ./build_fpdb.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-windows
        path: fpdb-3/dist/fpdb