name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
        cd fpdb-3
        python -m pip install -r requirements.txt
    
    - name: Build project
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = "Stop"
        
        # Build poker-eval
        cd ./fpdb-3/pypoker-eval/poker-eval
        if (!(Test-Path -Path "build")) {
            New-Item -ItemType Directory -Force -Path "build"
        }
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        cd ../../../..
        
        # Build pypoker-eval
        cd ./fpdb-3/pypoker-eval
        Copy-Item ".\pokereval.py" "..\pokereval.py"
        if (!(Test-Path -Path "build")) {
            New-Item -ItemType Directory -Force -Path "build"
        }
        cd build
        $pythonExe = "${{ env.pythonLocation }}\python.exe"
        $pythonInclude = "${{ env.pythonLocation }}\include"
        $pythonLib = "${{ env.pythonLocation }}\libs\python311.lib"
        $pokerEvalLib = "$env:GITHUB_WORKSPACE\fpdb-3\pypoker-eval\poker-eval\build\Release\poker_lib_static.lib"
        cmake .. -G "Visual Studio 17 2022" -A x64 -DPython3_EXECUTABLE=$pythonExe -DPython3_INCLUDE_DIR=$pythonInclude -DPython3_LIBRARY=$pythonLib -DPOKER_EVAL_LIBRARY=$pokerEvalLib -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release
        cd ..
        Copy-Item ".\build\Release\pypokereval.pyd" ".\_pokereval_3_11.pyd" -Force
    
    - name: Install PyInstaller
      run: pip install pyinstaller
    
    - name: Build fpdb-3
      run: |
        chmaod +x build_fpdb.sh
        ./build_fpdb.sh
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-windows
        path: fpdb-3/dist/fpdb