name: Build Projects
on:
  push:
    branches:
      - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements-linux.txt
    - name: Build projects
      run: |
        chmod +x build.sh
        ./build.sh
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-linux
        path: dist/*

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      - name: Update PATH
        run: |
          echo "C:\hostedtoolcache\windows\Python\3.11.9\x64\Scripts;C:\hostedtoolcache\windows\Python\3.11.9\x64" >> $env:GITHUB_PATH
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.1
      - name: Install dependencies
        run: |
          cd fpdb-3
          pip install -r requirements.txt
      - name: Build projects
        run: |
          ./build.sh
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: fpdb-windows
          path: dist/*

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    - name: Install dependencies
      run: |
        brew install cmake
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements-macos.txt
    - name: Build projects
      run: |
        chmod +x build.sh
        ./build.sh
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-macos
        path: dist/fpdb3.app

  build-macos-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.9'
    - name: Install dependencies
      run: |
        brew install cmake
        python -m pip install --upgrade pip
        cd fpdb-3
        pip install -r requirements-macos.txt
    - name: Build projects
      run: |
        chmod +x build.sh
        arch -arm64 ./build.sh
    - name: Upload macOS ARM artifact
      uses: actions/upload-artifact@v3
      with:
        name: fpdb-macos-arm
        path: dist/*