name: Build and Package fpdb-3, pypoker-eval, and poker-eval

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          git submodule update --init --recursive
          pip install -r fpdb-3/requirements.txt


      - name: Rendre le script exécutable
        run: chmod +x ./build.sh
        shell: bash

      - name: Build fpdb-3
        run: bash ./build_fpdb.sh
        shell: bash

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-windows
          path: dist/*
