name: Build and Package fpdb-3, pypoker-eval, and poker-eval

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          git submodule update --init --recursive
          pip install -r fpdb-3/requirements.txt


      - name: Rendre le script exécutable
        run: chmod +x ./build.sh
        shell: bash

      - name: Build fpdb-3
        run: bash ./build.sh
        shell: bash

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-windows
          path: fpdb-3/dist/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          git submodule update --init --recursive
          pip install -r fpdb-3/requirements-linux.txt

      - name: Rendre le script exécutable
        run: chmod +x ./build.sh
        shell: bash
      - name: Rendre le script exécutable
        run: chmod +x ./build_fpdb-linux.sh
        shell: bash

      - name: Build fpdb-3
        run: bash ./build.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-linux
          path: fpdb-3/dist/*

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          brew install cmake
          git submodule update --init --recursive
          pip install -r fpdb-3/requirements_macos.txt

      - name: Rendre le script exécutable
        run: chmod +x ./build.sh
        shell: bash
      - name: Rendre le script exécutable
        run: chmod +x ./build_fpdb-osx.sh
        shell: bash

      - name: Build fpdb-3
        run: bash ./build.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-macos
          path: fpdb-3/dist/*

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          brew install cmake
          git submodule update --init --recursive
          pip install -r fpdb-3/requirements_macos.txt

      - name: Rendre le script exécutable
        run: chmod +x ./build.sh
        shell: bash
      - name: Rendre le script exécutable
        run: chmod +x ./build_fpdb-osx.sh
        shell: bash

      - name: Build fpdb-3
        run: |
          export ARCHFLAGS="-arch arm64"
          bash ./build.sh
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-macos-arm
          path: fpdb-3/dist/*